# Generated by Django 4.0.3 on 2022-04-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image2',
            new_name='image_two',
        ),
    ]
