# Generated by Django 4.0.3 on 2022-04-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
    ]
