# Generated by Django 4.0.3 on 2022-04-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.FloatField(default=0),
        ),
    ]
