# Generated by Django 4.0.3 on 2022-04-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='whoIsFollowing',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed',
            new_name='whoToFollow',
        ),
    ]
