# Generated by Django 4.0.3 on 2022-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0004_alter_rating_content_alter_rating_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_content',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_design',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='average_usability',
            field=models.FloatField(default=0),
        ),
    ]
