# Generated by Django 4.0.3 on 2022-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0005_project_average_content_project_average_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
