# Generated by Django 4.0.3 on 2022-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0006_project_average_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='average_content',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_design',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_usability',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
