# Generated by Django 4.0.3 on 2022-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0007_alter_project_average_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_design',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='average_usability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(null=True),
        ),
    ]
