# Generated by Django 4.0.3 on 2022-04-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0008_alter_profile_followers_alter_profile_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creativity_content',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='creativity',
            field=models.IntegerField(null=True),
        ),
    ]
