# Generated by Django 4.0.3 on 2022-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0009_project_creativity_content_rating_creativity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
