# Generated by Django 4.0.3 on 2022-04-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0010_profile_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-when'], 'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='creativity_content',
            new_name='average_creativity',
        ),
    ]
