# Generated by Django 4.0.3 on 2022-04-11 09:09

import awardx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardx', '0013_alter_rating_content_alter_rating_creativity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=awardx.models.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='creativity',
            field=awardx.models.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=awardx.models.IntegerRangeField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=awardx.models.IntegerRangeField(null=True),
        ),
    ]
